version: "3.9"

services:
  backend:
    build: mov-rec-back
    command: bash -c "python ./app/create_tables.py && python ./app/__main__.py"
    environment:
      DATABASE_URL: "postgresql://postgres:password@database:5432/MovRec"
      DEVELOPMENT_MODE: 1
      SERVER_PORT: 8000
      ROOT_PATH: "/api"
    depends_on:
      - database
    restart: on-failure
    ports:
      - 8000:8000
  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: MovRec
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
  proxy:
    build: proxy
    ports:
      - 81:80
  frontend:
    build: mov-rec-front

volumes:
  pg_data: {}
